module:
  hugoVersion:
    min: '0.64.0'
  mounts:
    - source: page/index.md
      target: content/mods/jamicons.md
    - source: page/template.html
      target: layouts/_default/jamicons.html
    - source: partials
      target: layouts/partials/jam
  imports:
    - path: github.com/michaelampr/jam
      mounts:
        - source: icons
          target: assets/jam/icons
